server:
  port: 8888
  session-timeout: 60

spring:
  profiles:
    active: dev, redis
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://47.100.254.31:3306/mingyue_01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&serverTimezone=GMT%2B8&useSSL=false&requireSSL=false
      username: root
      password: mlJMB281yi9rYTuHCR
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


#mybatis配置
mybatis:
  mapper-locations: classpath:com/dbnewyouth/mingyue/**/mapper/xml/**.xml
  type-aliases-package: com.dbnewyouth.mingyue
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    cn.dbnewyouth.permission: debug

